services:
  redis:
    image: "redis:latest"
    container_name: "redis"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]

  postgresql:
    image: bitnami/postgresql:16.3.0
    environment:
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME:-postgres}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD:-password}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE:-bulk-searching}
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:password@localhost:5432/bulk-searching}
    ports:
      - '5432:5432'

volumes:
  redis-data:
    driver: local